import Link from "next/link";
import { notFound } from "next/navigation";
import { updateCustomerInquiryStatus } from "@/lib/actions";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatDate } from "@/lib/format";
import { canConvertCustomerInquiryItems, formatCustomerInquiryStatus } from "@/lib/customer-inquiry";

export default async function CustomerInquiryDetailPage({ params }: { params: Promise<{ inquiryId: string }> }) {
  const { inquiryId } = await params;
  const inquiry = await prisma.customerInquiry.findUnique({ where: { id: inquiryId }, include: { customer: true, items: { include: { product: true } }, salesOrder: true } });
  if (!inquiry) notFound();
  const canConvert = inquiry.status === "Open" && canConvertCustomerInquiryItems(inquiry.items);
  return <><PageHeader title={inquiry.inquiryNumber} description={`${inquiry.customer.companyName} - received ${formatDate(inquiry.inquiryDate)}`} /><section className="rounded-md border border-line bg-white p-5 shadow-soft"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Inquiry Detail</h2><StatusBadge status={formatCustomerInquiryStatus(inquiry.status)} /></div><div className="mb-5 grid gap-4 text-sm md:grid-cols-3"><div><p className="text-slate-500">Needed By</p><p className="font-medium">{inquiry.neededBy ? formatDate(inquiry.neededBy) : "-"}</p></div><div><p className="text-slate-500">Notes</p><p className="font-medium">{inquiry.notes || "-"}</p></div><div><p className="text-slate-500">Status Note</p><p className="font-medium">{inquiry.statusNote || "-"}</p></div></div><table><thead className="border-b border-line text-left text-xs uppercase text-slate-500"><tr><th className="py-3 pr-4">Item</th><th className="py-3 pr-4">Qty</th><th className="py-3 pr-4">Requested</th><th className="py-3">Agreed</th></tr></thead><tbody className="divide-y divide-line">{inquiry.items.map((item) => <tr key={item.id}><td className="py-3 pr-4">{item.itemName}</td><td className="py-3 pr-4">{item.quantity}</td><td className="py-3 pr-4">{item.requestedPrice === null ? "-" : formatCurrency(item.requestedPrice)}</td><td className="py-3">{item.agreedPrice === null ? "-" : formatCurrency(item.agreedPrice)}</td></tr>)}</tbody></table><div className="mt-6 space-y-4 border-t border-line pt-5">{canConvert && <div className="flex flex-wrap gap-3"><Link href={`/sales-orders?mode=create&inquiryId=${inquiry.id}`} className="inline-flex h-10 items-center justify-center rounded-md bg-brand px-4 text-sm font-semibold text-white">Convert to Sales Order</Link><Link href={`/pre-orders?mode=create&inquiryId=${inquiry.id}`} className="inline-flex h-10 items-center justify-center rounded-md border border-line px-4 text-sm font-semibold text-brand">Convert to Pre Order</Link></div>}{inquiry.status === "Open" && <div className="grid gap-3 lg:grid-cols-2"><StatusForm inquiryId={inquiry.id} status="Closed" label="Close Inquiry" placeholder="Reason: price agreement or required date could not be met" /><StatusForm inquiryId={inquiry.id} status="Cancelled" label="Cancel Inquiry" placeholder="Cancellation reason" /></div>}{inquiry.salesOrder && <Link href={`/sales-orders/${inquiry.salesOrder.id}`} className="inline-flex h-10 items-center justify-center rounded-md border border-line px-4 text-sm font-semibold text-brand">View Linked Order</Link>}</div>{!canConvert && inquiry.status === "Open" && <p className="mt-4 text-sm text-amber-700">To convert, link every item to an active product and enter an agreed price.</p>}</section></>;
}

function StatusForm({ inquiryId, status, label, placeholder }: { inquiryId: string; status: "Closed" | "Cancelled"; label: string; placeholder: string }) { return <form action={updateCustomerInquiryStatus} className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><input type="hidden" name="inquiryId" value={inquiryId} /><input type="hidden" name="status" value={status} /><input required name="statusNote" placeholder={placeholder} className="h-10 min-w-0 rounded-md border border-line px-3 text-sm" /><button className={status === "Cancelled" ? "h-10 rounded-md border border-rose-200 px-4 text-sm font-semibold text-rose-700" : "h-10 rounded-md border border-line px-4 text-sm font-semibold text-slate-700"}>{label}</button></form>; }
